id: I938A8D8B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T06:30:38+00:00'
last_modified: '2022-06-08T16:45:37.714125+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ1043
  title: གྲུབ་ཐོབ་གླིང་རས་ཀྱི་རྣམ་མགུར་མཐོང་བ་དོན་ལྡན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '8867':
      image_group_id: I1KG13518
      title: ''
      total_pages: 124
      order: 1
      base_file: 8867.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
